import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import GlobalCssPriority from "./components/GlobalStyleProvider/GlobalStyleProvider";
import { Poppins } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

const poppins = Poppins({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <GlobalCssPriority>{children}</GlobalCssPriority>
      </body>
    </html>
  );
}
